version: '3'

services:
  db:
    image: postgres
    container_name: freelasApp_db
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: postgres
      POSTGRES_DB: encoder
    ports:
      - 5434:5432

  app:
    build: .
    container_name: freelasApp
    ports:
      - 3333:80
    volumes:
      - .:/home/node/app
